# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GLCM.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1159, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GraphWidget = PlotWidget(self.centralwidget)
        self.GraphWidget.setGeometry(QtCore.QRect(260, 90, 511, 428))
        self.GraphWidget.setObjectName("GraphWidget")
        self.widget = QtWidgets.QWidget(self.GraphWidget)
        self.widget.setGeometry(QtCore.QRect(30, 40, 251, 211))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.GraphWidget)
        self.label.setGeometry(QtCore.QRect(320, 50, 151, 191))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 30, 242, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.load = QtWidgets.QPushButton(self.layoutWidget)
        self.load.setObjectName("load")
        self.horizontalLayout.addWidget(self.load)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 20, 256, 521))
        self.listWidget.setObjectName("listWidget")
        self.angle_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.angle_1.setGeometry(QtCore.QRect(1020, 220, 81, 20))
        self.angle_1.setObjectName("angle_1")
        self.angle_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.angle_2.setGeometry(QtCore.QRect(980, 170, 81, 20))
        self.angle_2.setObjectName("angle_2")
        self.angle_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.angle_3.setGeometry(QtCore.QRect(910, 140, 81, 20))
        self.angle_3.setObjectName("angle_3")
        self.angle_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.angle_4.setGeometry(QtCore.QRect(820, 160, 81, 20))
        self.angle_4.setObjectName("angle_4")
        self.angle_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.angle_5.setGeometry(QtCore.QRect(780, 220, 81, 20))
        self.angle_5.setObjectName("angle_5")
        self.angle_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.angle_6.setGeometry(QtCore.QRect(810, 270, 81, 20))
        self.angle_6.setObjectName("angle_6")
        self.angle_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.angle_7.setGeometry(QtCore.QRect(890, 300, 81, 20))
        self.angle_7.setObjectName("angle_7")
        self.angle_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.angle_8.setGeometry(QtCore.QRect(970, 270, 81, 20))
        self.angle_8.setObjectName("angle_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1159, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openfile = QtWidgets.QAction(MainWindow)
        self.openfile.setObjectName("openfile")
        self.savefile = QtWidgets.QAction(MainWindow)
        self.savefile.setObjectName("savefile")
        self.menu.addAction(self.openfile)
        self.menu.addAction(self.savefile)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "МПС"))
        self.load.setText(_translate("MainWindow", "load"))
        self.angle_1.setText(_translate("MainWindow", "0"))
        self.angle_2.setText(_translate("MainWindow", "45"))
        self.angle_3.setText(_translate("MainWindow", "90"))
        self.angle_4.setText(_translate("MainWindow", "135"))
        self.angle_5.setText(_translate("MainWindow", "180"))
        self.angle_6.setText(_translate("MainWindow", "225"))
        self.angle_7.setText(_translate("MainWindow", "270"))
        self.angle_8.setText(_translate("MainWindow", "315"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.openfile.setText(_translate("MainWindow", "Открыть"))
        self.savefile.setText(_translate("MainWindow", "Сохранить"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
